### ISSUE TITLE
Repo url in NuGet package

### ISSUE THREAD

**Issue by hansmbakker** [RoguePlanetoid/Spotify-NetStandard#3]
The [NuGet package](https://www.nuget.org/packages/Spotify.NetStandard/) links to https://github.com/RoguePlanetoid/SpotifyNetStandard while your repo is at https://github.com/RoguePlanetoid/Spotify-NetStandard (difference is the hyphen)

**Comment by RoguePlanetoid** [comment]
Thanks for that! I'll update this - I had changed the Url and forgot to update this, next version will have this corrected!

**Comment by RoguePlanetoid** [comment]
This issue has been resolved
